--- #Creation of Directory

- hosts: webservers
  user: ansible
  become: yes
  connection: ssh

  tasks:
    -  name: Creating a Directory
       file:
         path: /home/ansible/ramdir  
         state: directory
