--- #Deleting a file
- name: Deleting a file
  hosts: all
  become: yes
  connection: ssh
  user: ansible


  tasks:
    - name: deleting a file
      file:
        path:  /home/ansible/demofile
        state: absent  
