--- # s/w installation
- name: my playbook
  hosts: all
  become: true
  user: ansible
  connection: ssh

  tasks: 
    - name: Install packges into hosts
      yum:
        name: tree
        state: present  
