--- # my variable section

- hosts: all
  user: ansible
  become: true
  connection: ssh


  vars:
    pkgname: httpd

  
  tasks:
    - name: Install httpd on webservers
      action: yum name = '{{pkgname}}' state=installed
      
